### ISSUE TITLE
Feature: Show list of contributors

### ISSUE THREAD

**Issue by hansemannn** [hansemannn/studentenfutter-app#14]
The app should have another list item "Contributors" in the settings that uses the Github REST-API to fetch contributors of this project inside a list with an avatar + title. 

@nuno Something you could think of?

**Comment by nuno** [comment]
Sure! Love the idea.

**Comment by hansemannn** [comment]
This is the required call: https://api.github.com/repos/hansemannn/studentenfutter-app/contributors

**Comment by hansemannn** [comment]
I think it doesn't require auth!

**Comment by nuno** [comment]
Depends how many request we have by hour I think, if I remember correct.

**Comment by hansemannn** [comment]
Should looked it up using [/rate_limit](https://api.github.com/rate_limit), looks like 60 requests per user per our. That's **fine** for this API I guess, because a) not all users of the app will check the contributors every day and b) not 61x an hour.

**Comment by nuno** [comment]
Work on it now
