### ISSUE TITLE
[ERROR] :  TypeError: undefined is not a function (evaluating 'dateutils.getFormattedDate()')

### ISSUE THREAD

**Issue by nuno** [hansemannn/studentenfutter-app#2]
Hey @hansemannn  with "LiveView" enabled the app not open on simulator.
Works ok without "LiveView"

Appcelerator Studio, build: 4.8.1.201612050850
appc v6.1.0
node v4.4.7
titanium sdk 6.0.1
simulator iphone 7 - v10.1
xcode 8.1 - 8B62

[INFO] :   [LiveView] Error Evaluating app.js @ Line: 63
[ERROR] :  TypeError: undefined is not a function (evaluating 'dateutils.getFormattedDate()')
[ERROR] :  File: app.js
[ERROR] :  Line: 63
[ERROR] :  SourceId: <null>
[ERROR] :  Backtrace:
[ERROR] :   undefined

**Comment by hansemannn** [comment]
Thx @nuno! Fixed some missing `/` prefixes and changed the exports statement of that file. Can you try?

**Comment by nuno** [comment]
Testing now!

https://github.com/hansemannn/studentenfutter-app/blob/3a27dfbc9e5797690780b9d9b3c66f5f8a10cdba/app/controllers/lunches/list.js#L327

missing  semicolon  on "open "
