### ISSUE TITLE
Pull to refresh after [ERROR]

### ISSUE THREAD

**Issue by nuno** [hansemannn/studentenfutter-app#3]
Hey @hansemannn  after this commit https://github.com/hansemannn/studentenfutter-app/commit/3a27dfbc9e5797690780b9d9b3c66f5f8a10cdba   ~~Liveview is fixed but~~ "Pull to refresh"  stopped:

[INFO] :   [GET https://api.studentenfutter-os.de/lunches/list/2017-01-14/0]
[ERROR] :  Script Error {
[ERROR] :      column = 47;
[ERROR] :      line = 39;
[ERROR] :      message = "undefined is not a function (evaluating 'require(\"/auth\").getCredentials()')";
[ERROR] :      stack = "getCredentials\nrefreshCache\nload\ngetLunches\nfetchData\nonRefreshStart";
[ERROR] :  }

[http://sharebucketapp.com/E3MWI5ZTVjYzRiZTQ4MD](http://sharebucketapp.com/E3MWI5ZTVjYzRiZTQ4MD)

**Comment by nuno** [comment]
auth lib missing, so there is no external api connection right?
NOTES:
Error just happen on Liveview enabled!

**Comment by hansemannn** [comment]
yes, but it should usually catch the error for the open source build. Will check

**Comment by hansemannn** [comment]
Fixed in recent commits!
