### ISSUE TITLE
External api explanation :)

### ISSUE THREAD

**Issue by nuno** [hansemannn/studentenfutter-app#4]
Any chance to explain how the  external api should work, so we can kinda of simulate better this fantastic app?  Thanks @hansemannn

**Comment by hansemannn** [comment]
Well, the API collects lunch data from the universities website, refactors it and returns it as JSON. The API used a basic authentication to secure the endpoint and the credential are kept private for now. So for every day, it returns something else (or nothing on the weekend when the canteens are closed).
